# Generated by Django 5.2.3 on 2025-07-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check_list',
            field=models.ManyToManyField(blank=True, related_name='task_check_lists', to='core.checklist'),
        ),
    ]
