# Generated by Django 5.2.3 on 2025-07-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_task_check_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='core.task'),
        ),
    ]
