# Generated by Django 5.2.3 on 2025-07-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projectinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvite',
            name='title',
        ),
    ]
