# Generated by Django 5.2.3 on 2025-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_projectinvite_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvite',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20, null=True),
        ),
    ]
